---
title: "PA1_template"
author: "Aaron Traub"
date: "May 25, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reproducable Data Assignment 1 (week 2)
### By Aaron Traub



Dataset: Activity monitoring data [52K]

Forked from: (http://github.com/rdpeng/RepData_PeerAssessment1). 
**Note:** dataset is download from the repo on 25 May 2016


### Loading and preprocessing the data
```{r load-data }
    library (dplyr)
    # Load data
    zipPath <- "./activity.zip"
    filePath <- "./activity.csv"
    unzip(zipPath)
    activity <- read.csv(filePath, header = TRUE)
    
    # convert date column to a date object
    activity$date <- as.Date(activity$date, format = "%Y-%m-%d" )
```


```{r summaryCalc}
    # Calculate values
    meanSteps <- activity %>% group_by(date) %>% summarize  (mean(steps, na.rm =TRUE)) 
    names(meanSteps) <- c("date","steps")
    
    medianSteps <- activity %>% group_by(date) %>% summarize  (median(steps, na.rm =TRUE))
   
    sumSteps <- activity %>% group_by(date) %>% summarize  (sum(steps, na.rm =TRUE)) 
    names(sumSteps) <- c("date","steps")
    
       
```
###**Histogram** of the **total** number, **mean** & **median** of steps taken each day
``` {r histMeanSteps}
    hist(sumSteps$steps, breaks= 15, col="pink",xlab="# of Steps", main="Figure 1: Daily Steps")
    print (meanSteps)
    print (medianSteps)
```


###Time series plot of the average number of steps taken 
``` {r fivemin}
    meanStepsI <- activity %>% group_by(interval) %>% summarize (mean(steps, na.rm =TRUE)) 
    plot(meanStepsI, type="l", ylab="# of Steps", xlab="5 Minute Interval", col="cornflowerblue",  main="Figure 2: Daily Steps for Each Increment")
   max(meanStepsI) 
```

``` {r impute}
    numNA <- sum(is.na(activity)) 
    # meanNA <- mean(is.na(activity$steps))
    activityCount <- nrow(activity)
    # make a second variable
    activity2 <- activity
```
Number of NA values: `r numNA`
